import type { Metadata } from "next";
import localFont from "next/font/local";

const leMurmure = localFont({
  src: "../../public/fonts/Le_Murmure.woff2",
  variable: "--font-le-murmure",
  display: "swap",
});
import "./globals.css";
import React from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={leMurmure.variable}>
      <body>{children}</body>
    </html>
  );
}
